// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIuRPLjIMsiVTK4TNmJkgczeWMLOwEbJw',
    appId: '1:789401795798:web:de1cc616a37d0db7591d77',
    messagingSenderId: '789401795798',
    projectId: 'instagram-clone-6a8d7',
    authDomain: 'instagram-clone-6a8d7.firebaseapp.com',
    storageBucket: 'instagram-clone-6a8d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlAevTMGWwWzWABg74ruJM39dROgLqC24',
    appId: '1:789401795798:android:7b482c6054a9b4b5591d77',
    messagingSenderId: '789401795798',
    projectId: 'instagram-clone-6a8d7',
    storageBucket: 'instagram-clone-6a8d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkL3jQgeRrhDfQaioYqaF9JO8wX3npb8c',
    appId: '1:789401795798:ios:80e32052118cb8a9591d77',
    messagingSenderId: '789401795798',
    projectId: 'instagram-clone-6a8d7',
    storageBucket: 'instagram-clone-6a8d7.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkL3jQgeRrhDfQaioYqaF9JO8wX3npb8c',
    appId: '1:789401795798:ios:d9374d9a50384d9b591d77',
    messagingSenderId: '789401795798',
    projectId: 'instagram-clone-6a8d7',
    storageBucket: 'instagram-clone-6a8d7.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
